org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod_name=Screenshot Message Enhancer
mod_id=screenshotmessageenhancer
mod_version=2.0.0
mod_description=Enhance screenshot messages with COPY, OPEN, OPEN FOLDER and DELETE buttons
mod_archives_name=ScreenshotMessageEnhancer
base_group=tomeko.screenshotmessageenhancer

java_version=[VERSIONED]
minecraft_version=[VERSIONED]
fabric_loader_version=0.19.3
fabric_api_version=[VERSIONED]
fabric_language_kotlin_version=1.13.13+kotlin.2.4.10

stonecutter_version=0.9.7

oneconfig_version=1.1.4
mod_menu_version=[VERSIONED]

java_objective_c_bridge_version=1.2